# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Badge.create(name: 'Rookie', image: '/Rookie.png', exp: '1')
Badge.create(name: 'Bronze', image: '/Bronze.png', exp: '5')
Badge.create(name: 'Silver', image: '/Silver.png', exp: '10')
Badge.create(name: 'Gold', image: '/Gold.png', exp: '15')
Badge.create(name: 'Platinum', image: '/Platinum.png', exp: '20')

Topic.create(name: 'C#')
Topic.create(name: 'C++')
Topic.create(name: 'RUBY')
Topic.create(name: 'PYTHON')
Topic.create(name: 'VISUAL BASIC')
Topic.create(name: 'PROLOG')
Topic.create(name: 'ANDROID')

Dicctionarytopic.create(main_topic_id: '1', secondary_name: 'C SHARP')
Dicctionarytopic.create(main_topic_id: '1', secondary_name: 'CSHARP')
Dicctionarytopic.create(main_topic_id: '1', secondary_name: 'C #')
Dicctionarytopic.create(main_topic_id: '1', secondary_name: 'C 3')
Dicctionarytopic.create(main_topic_id: '1', secondary_name: 'C3')
Dicctionarytopic.create(main_topic_id: '2', secondary_name: 'C+ +')
Dicctionarytopic.create(main_topic_id: '2', secondary_name: 'C + +')
Dicctionarytopic.create(main_topic_id: '2', secondary_name: 'C ++')
Dicctionarytopic.create(main_topic_id: '2', secondary_name: 'CMASMAS')
Dicctionarytopic.create(main_topic_id: '2', secondary_name: 'C MAS MAS')
Dicctionarytopic.create(main_topic_id: '2', secondary_name: 'CMAS MAS')
Dicctionarytopic.create(main_topic_id: '2', secondary_name: 'C MASMAS')
Dicctionarytopic.create(main_topic_id: '2', secondary_name: 'CPLUSPLUS')
Dicctionarytopic.create(main_topic_id: '2', secondary_name: 'C PLUS PLUS')
Dicctionarytopic.create(main_topic_id: '2', secondary_name: 'CPLUS PLUS')
Dicctionarytopic.create(main_topic_id: '2', secondary_name: 'C PLUS PLUS')
Dicctionarytopic.create(main_topic_id: '3', secondary_name: 'RUBI')
Dicctionarytopic.create(main_topic_id: '3', secondary_name: 'RWBY')
Dicctionarytopic.create(main_topic_id: '4', secondary_name: 'PHYTHON')
Dicctionarytopic.create(main_topic_id: '4', secondary_name: 'PHYTON')
Dicctionarytopic.create(main_topic_id: '4', secondary_name: 'PITON')
Dicctionarytopic.create(main_topic_id: '4', secondary_name: 'PHITON')
Dicctionarytopic.create(main_topic_id: '4', secondary_name: 'PHITHON')
Dicctionarytopic.create(main_topic_id: '5', secondary_name: 'VISUALBASIC')
Dicctionarytopic.create(main_topic_id: '5', secondary_name: 'VISUALVASIC')
Dicctionarytopic.create(main_topic_id: '5', secondary_name: 'BISUALBASIC')
Dicctionarytopic.create(main_topic_id: '5', secondary_name: 'BISUALVASIC')
Dicctionarytopic.create(main_topic_id: '5', secondary_name: 'VISUAL VASIC')
Dicctionarytopic.create(main_topic_id: '5', secondary_name: 'BISUAL BASIC')
Dicctionarytopic.create(main_topic_id: '5', secondary_name: 'BISUAL VASIC')
Dicctionarytopic.create(main_topic_id: '6', secondary_name: 'PROLOL')
Dicctionarytopic.create(main_topic_id: '6', secondary_name: 'PRO LOG')
Dicctionarytopic.create(main_topic_id: '7', secondary_name: 'ANDRIOD')


